#!/usr/bin/env Rscript --vanilla

library(methods)

# library(staticdocs)
# build_package(".", "/tmp/pkgdocs")

wd = getwd()
pkg.name = basename(wd)
setwd("/tmp/pkgdocs")
try ({
  library(knitr)
  require(pkg.name, character.only=TRUE)
  knit_rd(pkg.name)
})
setwd(wd)

# vim: ft=r
